### ISSUE TITLE
[Kuba] Documentation in Wiki

### ISSUE THREAD

**Issue by SzymonKowalczyk** [Kurii957/Example#14]
As part of the epic: Sample Maven Java application investigation #7

Create Wiki page where there will be all link to:

Sample Spring app
Where to download Java and version
How to setup java on windows link with title
Where to download maven and version

**Comment by Kurii957** [comment]
Link to Wiki page: https://github.com/Kurii957/Example/wiki/Helpful-links---Java,-Maven,-Sample-Spring-app
